### ISSUE TITLE
how to call function or action?

### ISSUE THREAD

**Issue by ramifi** [jaystack/odata-v4-mongodb#10]
Hi
How can I call a function or an action in the controller by web request?
For example the getCheapest() function

**Comment by lazarv** [comment]
Hi @ramifi,
by using the standard OData way, reference the function or action with namespace, like ```/Products/Northwind.getCheapest()```. By the way this question belongs into the main [odata-v4-server](https://github.com/jaystack/odata-v4-server) library, it's not related to the mongodb connector.
