### ISSUE TITLE
Regex special characters are not escaped

### ISSUE THREAD

**Issue by MathieuCouette** [jaystack/odata-v4-mongodb#13]
The second argument of a `contains`, `endswith` or `startswith` method call should be regex escaped before being used to create a regex. Otherwise, the method call `contains(A, '.')` results in the regex `/./gi`, which matches any one character instead of just `.`.

**Comment by WandererInVoids** [comment]
i create package with fix,
@MathieuCouette I used urs fix 
https://github.com/WandererInVoids/odata-v4-mongodb 
https://www.npmjs.com/package/@wandererin/odata-v4-mongodb
