### ISSUE TITLE
invalid createQuery result if used or, contains and eq

### ISSUE THREAD

**Issue by andriy-f** [jaystack/odata-v4-mongodb#5]
Hi,

function createQuery produces invalid result if supplied with following query:
filter=contains(Name,'be') or Name eq 'Produce'

Input:
http://odata-v4-demo.jaystack.net/api/Categories?$filter=contains(Name,'be') or Name eq 'Produce'

Output:
{
  "@odata.context": "http://odata-v4-demo.jaystack.net/api/$metadata#Categories",
  "value": [
    {
      "@odata.id": "http://odata-v4-demo.jaystack.net/api/Categories('578f2baa12eaebabec4af289')",
      "@odata.editLink": "http://odata-v4-demo.jaystack.net/api/Categories('578f2baa12eaebabec4af289')",
      "_id": "578f2baa12eaebabec4af289",
      "Description": "Soft drinks",
      "Name": "Beverages"
    }
  ]
}

i.e. one element is missing ('Produce' category)

**Comment by andriy-f** [comment]
O I see someone fixed it by some recent commit (it's in sources but not published yet. Waiting for release!

**Comment by andriy-f** [comment]
It was fixed by this PR https://github.com/jaystack/odata-v4-mongodb/pull/4. It's not on npm yet

**Comment by aaghevli** [comment]
I believe this has been merged and available in version 1.11. Can you confirm?

**Comment by andriy-f** [comment]
yes. it's fixed. Thanks!

**Comment by andriy-f** [comment]
I guess I should wait until PR is merged

**Comment by aaghevli** [comment]
The PR #4 is merged and the latest npm version updated as far as I know.

**Comment by andriy-f** [comment]
And this PR https://github.com/jaystack/odata-v4-mongodb/pull/7 ?

**Comment by aaghevli** [comment]
Huh strange. I think someone updated independent of that PR #7 so we should be good to go. 

https://github.com/jaystack/odata-v4-mongodb/blob/master/package.json#L3

**Comment by andriy-f** [comment]
Closing then. Thanks
