### ISSUE TITLE
filtering with combination of contains and tolower doesn't work

### ISSUE THREAD

**Issue by andriy-f** [jaystack/odata-v4-mongodb#9]
Hi, filtering with combination of contains and tolower doesn't return expected results. 
version: 0.1.11
example request ?$filter=contains(tolower(Name), 'pro')

**Comment by lazarv** [comment]
Hi @andriy-f,
the ```tolower``` method call expression is not implemented in the mongodb connector. It should throw an error.

**Comment by andriy-f** [comment]
It doesn't throw error at the moment. It returns all records

**Comment by lazarv** [comment]
@andriy-f the fix is available on npm, please use latest version (0.1.12).

**Comment by andriy-f** [comment]
Indeed. Thanks.
